on:
  push:

jobs:
  transfer-file-between-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: dbt
      
      - name: Generate file
        run: |
          echo "Hello from feature branch" > saved.txt

      - name: Move file to temp dir
        run: |
          mkdir -p /tmp/mydata
          mv saved.txt /tmp/mydata/

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Use the file from feature branch
        run: |
          cp /tmp/mydata/saved.txt .
          cat saved.txt
